# config/main_config.yaml
# Evo projesinin ana yapılandırma dosyası.
# Modül ayarları, genel parametreler ve diğer yapılandırmalar burada tanımlanır.

# Genel Ayarlar
cognitive_loop_interval: 0.1 # Bilişsel döngünün ne sıklıkta çalışacağı (saniye)

# Sense modülleri ayarları
vision:
  camera_index: 0 # Varsayılan kamera indeksi
  dummy_width: 640 # Simüle kare genişliği (gerçek kamera yoksa)
  dummy_height: 480 # Simüle kare yüksekliği (gerçek kamera yoksa)
  # is_dummy: True # Gerçek kamera yerine simülasyon kullanılsın mı? (Gelecek)

audio:
  audio_rate: 44100 # Ses örnekleme oranı
  audio_chunk_size: 1024 # Her seferinde işlenecek ses örneği sayısı
  # audio_input_device_index: null # null varsayılan cihazı kullanır, belirli bir index verilebilir.

# Processor modülleri ayarları
processors:
  vision:
    output_width: 64
    output_height: 64
    canny_low_threshold: 50 # Canny kenar tespiti düşük eşiği
    canny_high_threshold: 150 # Canny kenar tespiti yüksek eşiği
  audio:
    # output_dim: AudioProcessor'ın döndüreceği özellik sayısı (Enerji, Spectral Centroid).
    # Implementation şu an 2 özellik döndürüyor.
    output_dim: 2
    # audio_rate AudioSensor'dan gelebilir, ama burada da belirtilebilir.
    # audio_rate: 44100 # İsteğe bağlı olarak burada belirtilebilir

# Representation Learner ayarları
representation:
  # input_dim: Encoder'ın beklediği toplam girdi boyutu.
  # (VisionProcessor grayscale 64*64) + (VisionProcessor edges 64*64) + (AudioProcessor output_dim 2)
  # 4096 + 4096 + 2 = 8194
  input_dim: 8194
  representation_dim: 128 # Temsil vektörünün boyutu

# Memory modülleri ayarları
memory:
  max_memory_size: 1000 # Saklanacak maksimum temsil sayısı (core/working memory)
  num_retrieved_memories: 5 # Retrieve metodunda varsayılan olarak geri çağrılacak anı sayısı
  # Kalıcı depolama ayarları
  memory_file_path: data/core_memory.pkl # Belleğin kaydedileceği/yükleneceği dosya yolu. data/ dizini oluşturulacak.
  # retrieval_method: similarity # Gelecekte farklı method seçimi olabilir.

# Cognition modülleri ayarları
cognition:
  # Örneğin, karar eşikleri veya model yolları buraya gelebilir
  # decision_threshold: 0.7
  # familiarity_threshold: Girdiyi "tanıdık" kabul etmek için gereken en düşük bellek benzerlik skoru (0.0 ile 1.0 arası float).
  familiarity_threshold: 0.8 # Varsayılan değer

# Motor Control modülleri ayarları
motor_control:
  # Örneğin, çıktı tipi (metin, ses vb.) veya sentezleyici ayarları
  # default_output_type: text

# Interaction modülleri ayarları
interaction:
  enabled_channels: ['console'] # Aktif çıktı kanalları listesi. 'console', 'web_api' vb.
  channel_configs: # Kanal bazlı özel ayarlar
    web_api:
      port: 5000
      # host: 127.0.0.1 # Gelecekte

# Loglama Ayarları
logging:
  level: DEBUG # Varsayılan loglama seviyesi (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  # handlers: # Gelecekte farklı çıktı hedefleri tanımlanabilir
  #   - type: console
  #     level: DEBUG
  #   - type: file
  #     filename: evo.log
  #     level: INFO