# config/main_config.yaml
# Evo projesinin ana yapılandırma dosyası.
# Modül ayarları, genel parametreler ve diğer yapılandırmalar burada tanımlanır.

# Genel Ayarlar
cognitive_loop_interval: 0.1 # Bilişsel döngünün ne sıklıkta çalışacağı (saniye)

# Hesaplama Ayarları
compute:
  backend: "pytorch"  # "numpy", "pytorch", "tensorflow" (gelecekte)
  device: "cuda"      # "cpu", "cuda", "cuda:0", "mps" (PyTorch için)
                      # TensorFlow için farklı olabilir ("gpu:0" vb.)

# Sense modülleri ayarları
vision:
  camera_index: 0
  dummy_width: 640
  dummy_height: 480
  is_dummy: False
  process_color: True # VisionProcessor'ın renkli mi gri mi işleyeceğini belirler

audio:
  audio_rate: 44100
  audio_chunk_size: 1024
  audio_input_device_index: null
  is_dummy: False

# Processor modülleri ayarları
processors:
  vision:
    output_width: 64
    output_height: 64
    # output_channels, process_color True ise 3 (RGB), False ise 1 (Gri) olmalı.
    # VisionProcessor __init__ içinde process_color'a göre bunu doğrular/ayarlar.
    output_channels: 3 
    use_gpu_if_available: True # VisionProcessor'ın OpenCV sonrası tensörleri GPU'ya taşıması
    canny_low_threshold: 50
    canny_high_threshold: 150
  audio:
    # output_dim, AudioProcessor içindeki implementasyona göre belirlenir (şu an 2).
    # Bu ayar, uyarı/referans için kullanılabilir.
    output_dim: 2 
    audio_rate: 44100 # AudioSensor'dan gelen rate ile aynı olmalı (veya AudioProcessor yeniden örnekleme yapmalı)

# Representation Learner ayarları
representation:
  # input_dim, module_loader.py tarafından işlemci çıktılarına göre otomatik hesaplanır.
  # "auto" veya herhangi bir sayısal değer girilebilir, üzerine yazılacaktır.
  input_dim: "auto" 
  representation_dim: 128

# Memory modülleri ayarları
memory:
  max_memory_size: 1000
  num_retrieved_memories: 5
  memory_file_path: data/core_memory.pkl

# Cognition modülleri ayarları
cognition:
  familiarity_threshold: 0.8
  audio_energy_threshold: 1000.0
  visual_edges_threshold: 50.0
  brightness_threshold_high: 200.0
  brightness_threshold_low: 50.0
  curiosity_threshold: 5.0
  curiosity_increment_new: 1.0
  curiosity_decrement_familiar: 0.5
  curiosity_decay: 0.1
  concept_recognition_threshold: 0.85
  learning:
    concept_file_path: data/concepts.pkl
    learning_frequency: 100
    learning_memory_sample_size: 50
    new_concept_threshold: 0.7

# Motor Control modülleri ayarları
motor_control: {} # Spesifik ayarlar eklenebilir

# Interaction modülleri ayarları
interaction:
  enabled_channels:
    - console
  channel_configs:
    console: {}
    web_api:
      port: 5000
      host: "127.0.0.1"
      endpoint: "/output"

# Loglama Ayarları
logging:
  level: INFO
  handlers:
    - type: console
      level: INFO
      color: true
    - type: file
      filename: logs/all.log
      level: DEBUG
      color: false
    - type: socket
      host: 127.0.0.1
      port: 9000
      udp: true
      level: WARNING
  modules:
    src.core.compute_utils: DEBUG
    src.core.module_loader: DEBUG
    src.senses.vision: INFO # Veya DEBUG
    src.senses.audio: INFO  # Veya DEBUG
    src.processing.vision: DEBUG
    src.processing.audio: DEBUG
    src.representation.models: DEBUG
    src.memory.core: DEBUG
    src.cognition.core: DEBUG
    src.cognition.understanding: DEBUG
    src.cognition.decision: DEBUG
    src.cognition.learning: DEBUG
    src.motor_control.core: DEBUG
    src.motor_control.expression: DEBUG
    src.interaction.api: DEBUG
    src.interaction.output_channels.console: INFO
    src.interaction.output_channels.web_api: INFO
    __main__: INFO