# config/main_config.yaml
# Evo projesinin ana yapılandırma dosyası.
# Modül ayarları, genel parametreler ve diğer yapılandırmalar burada tanımlanır.

# Genel Ayarlar
cognitive_loop_interval: 0.1 # Bilişsel döngünün ne sıklıkta çalışacağı (saniye)

# Sense modülleri ayarları
vision:
  camera_index: 0 # Varsayılan kamera indeksi
  dummy_width: 640 # Simüle kare genişliği (gerçek kamera yoksa)
  dummy_height: 480 # Simüle kare yüksekliği (gerçek kamera yoksa)
  is_dummy: False # Gerçek kamera yerine simülasyon kullanılsın mı?

audio:
  audio_rate: 44100 # Ses örnekleme oranı
  audio_chunk_size: 1024 # Her seferinde işlenecek ses örneği sayısı
  audio_input_device_index: null # null varsayılan cihazı kullanır, belirli bir index verilebilir.
  is_dummy: False # Gerçek mikrofon yerine simülasyon kullanılsın mı?

# Processor modülleri ayarları
processors:
  vision:
    output_width: 64
    output_height: 64
    canny_low_threshold: 50 # Canny kenar tespiti düşük eşiği
    canny_high_threshold: 150 # Canny kenar tespiti yüksek eşiği
  audio:
    # output_dim: AudioProcessor'ın döndüreceği özellik sayısı (Enerji, Spectral Centroid).
    # Kod implementasyonu şu anda 2 özellik döndürüyor.
    output_dim: 2
    # audio_rate AudioSensor'dan gelebilir, ama burada da belirtilebilir.
    audio_rate: 44100 # İsteğe bağlı olarak burada belirtilebilir

# Representation Learner ayarları
representation:
  # input_dim: Encoder'ın beklediği toplam girdi boyutu.
  # (VisionProcessor grayscale 64*64) + (VisionProcessor edges 64*64) + (AudioProcessor output_dim 2)
  # 4096 + 4096 + 2 = 8194
  input_dim: 8194
  representation_dim: 128 # Temsil vektörünün boyutu

# Memory modülleri ayarları
memory:
  max_memory_size: 1000 # Saklanacak maksimum temsil sayısı (core/working memory)
  num_retrieved_memories: 5 # Retrieve metodunda varsayılan olarak geri çağrılacak anı sayısı
  memory_file_path: data/core_memory.pkl # Belleğin kaydedileceği/yükleneceği dosya yolu. data/ dizini oluşturulacak.

# Cognition modülleri ayarları
cognition:
  # Anlama (Understanding) ve Karar (Decision) ayarları
  familiarity_threshold: 0.8
  audio_energy_threshold: 1000.0
  visual_edges_threshold: 50.0
  brightness_threshold_high: 200.0
  brightness_threshold_low: 50.0
  # İçsel Durum (Curiosity - DecisionModule içinde kullanılır)
  curiosity_threshold: 5.0
  curiosity_increment_new: 1.0
  curiosity_decrement_familiar: 0.5
  curiosity_decay: 0.1
  # Kavram Tanıma eşiği (DecisionModule kullanır)
  concept_recognition_threshold: 0.85
  # Öğrenme (Learning) ayarları (LearningModule ve ilgili CognitionCore parametreleri)
  learning:
    concept_file_path: data/concepts.pkl # Öğrenilen kavramların kaydedileceği dosya yolu
    learning_frequency: 100 # Öğrenme sıklığı (her 100 döngüde bir öğrenme işlemi yapılır)
    learning_memory_sample_size: 50 # Öğrenme için bellekten alınacak örnek sayısı
    new_concept_threshold: 0.7 # Yeni bir kavramın oluşması için eşik

# Motor Control modülleri ayarları
motor_control:
  # default_output_type: text # Örnek ayar

# Interaction modülleri ayarları
interaction:
  enabled_channels:
    - console
    # - web_api
  channel_configs:
    console: {}
    web_api:
      port: 5000
      host: "127.0.0.1"  # Web API için host ve port ayarları
      endpoint: "/output" # API endpointi

# Loglama Ayarları
logging:
  level: INFO # Ana loglama seviyesi
  handlers:
    - type: console
      level: DEBUG # Konsol için daha detaylı loglama (geliştirme sırasında)
      color: true
    - type: file
      filename: logs/all.log
      level: DEBUG # Dosyaya tüm DEBUG logları
      color: false
    - type: socket
      host: 127.0.0.1
      port: 9000
      udp: true
      level: WARNING
  modules:
    # Belirli modüller için log seviyeleri override edilebilir
    src.senses.vision: DEBUG
    src.senses.audio: DEBUG
    src.processing.vision: DEBUG
    src.processing.audio: DEBUG
    src.representation.models: DEBUG
    src.memory.core: DEBUG
    src.cognition.core: DEBUG
    src.cognition.understanding: DEBUG
    src.cognition.decision: DEBUG
    src.cognition.learning: DEBUG
    src.motor_control.core: DEBUG
    src.motor_control.expression: DEBUG
    src.interaction.api: DEBUG
    src.interaction.output_channels.console: INFO # Konsol çıktısı kanalı için INFO
    src.interaction.output_channels.web_api: INFO

    # __main__ (test_module.py ve run_evo.py gibi scriptler için)
    __main__: INFO # Ana scriptler için varsayılan INFO, testlerde DEBUG olabilir