# config/main_config.yaml
# Evo projesinin ana yapılandırma dosyası.
# Modül ayarları, genel parametreler ve diğer yapılandırmalar burada tanımlanır.

# Genel Ayarlar
cognitive_loop_interval: 0.1 # Bilişsel döngünün ne sıklıkta çalışacağı (saniye)

# Sense modülleri ayarları
vision:
  camera_index: 0 # Varsayılan kamera indeksi
  dummy_width: 640 # Simüle kare genişliği (gerçek kamera yoksa)
  dummy_height: 480 # Simüle kare yüksekliği (gerçek kamera yoksa)
  is_dummy: False # Gerçek kamera yerine simülasyon kullanılsın mı?

audio:
  audio_rate: 44100 # Ses örnekleme oranı
  audio_chunk_size: 1024 # Her seferinde işlenecek ses örneği sayısı
  audio_input_device_index: null # null varsayılan cihazı kullanır, belirli bir index verilebilir.
  is_dummy: False # Gerçek mikrofon yerine simülasyon kullanılsın mı?

# Processor modülleri ayarları
processors:
  vision:
    output_width: 64
    output_height: 64
    canny_low_threshold: 50 # Canny kenar tespiti düşük eşiği
    canny_high_threshold: 150 # Canny kenar tespiti yüksek eşiği
  audio:
    # output_dim: AudioProcessor'ın döndüreceği özellik sayısı (Enerji, Spectral Centroid).
    # Implementation şu an 2 özellik döndürüyor.
    output_dim: 2
    # audio_rate AudioSensor'dan gelebilir, ama burada da belirtilebilir.
    audio_rate: 44100 # İsteğe bağlı olarak burada belirtilebilir

# Representation Learner ayarları
representation:
  # input_dim: Encoder'ın beklediği toplam girdi boyutu.
  # (VisionProcessor grayscale 64*64) + (VisionProcessor edges 64*64) + (AudioProcessor output_dim 2)
  # 4096 + 4096 + 2 = 8194
  input_dim: 8194
  representation_dim: 128 # Temsil vektörünün boyutu

# Memory modülleri ayarları
memory:
  max_memory_size: 1000 # Saklanacak maksimum temsil sayısı (core/working memory)
  num_retrieved_memories: 5 # Retrieve metodunda varsayılan olarak geri çağrılacak anı sayısı
  # Kalıcı depolama ayarları
  memory_file_path: data/core_memory.pkl # Belleğin kaydedileceği/yükleneceği dosya yolu. data/ dizini oluşturulacak.
  # retrieval_method: similarity # Gelecekte farklı method seçimi olabilir.

# Cognition modülleri ayarları
cognition:
  # Anlama (Understanding) ve Karar (Decision) ayarları
  familiarity_threshold: 0.8 # Varsayılan değer
  audio_energy_threshold: 1000.0 # Yüksek Ses Enerjisi Eşiği
  visual_edges_threshold: 50.0 # Yüksek Görsel Kenar Eşiği
  brightness_threshold_high: 200.0 # Parlak Ortam Eşiği
  brightness_threshold_low: 50.0 # Karanlık Ortam Eşiği
  # Öğrenme (Learning) ve Kavram Tanıma ayarları
  learning_frequency: 100
  learning_memory_sample_size: 50
  new_concept_threshold: 0.7
  concept_recognition_threshold: 0.85
  # İçsel Durum (Curiosity) ayarları
  curiosity_threshold: 5.0
  curiosity_increment_new: 1.0
  curiosity_decrement_familiar: 0.5
  curiosity_decay: 0.1
  learning:
    concept_file_path: data/concepts.pkl # Öğrenilen kavramların kaydedileceği dosya yolu
    learning_frequency: 100 # Öğrenme sıklığı (her 100 döngüde bir öğrenme işlemi yapılır)

# Motor Control modülleri ayarları
motor_control:
  # Örneğin, çıktı tipi (metin, ses vb.) veya sentezleyici ayarları
  # default_output_type: text

# Interaction modülleri ayarları
interaction:
  enabled_channels: ["console", "web_api"] # List of active output channels. 'console', 'web_api', etc.
  channel_configs: # Channel-specific settings
    console: {} # Console-specific settings can be left empty if none.
    web_api:
      port: 5000
      # host: 127.0.0.1 # Future

# Loglama Ayarları
logging:
  level: INFO
  handlers:
    - type: console
      level: DEBUG
      color: true
    - type: file
      filename: logs/evo_all.log
      level: DEBUG
      color: false
    # - type: webapi # Temporarily disabled for testing 'no output' issue
    #   url: http://localhost:5000/log
    #   level: ERROR
    - type: socket
      host: 127.0.0.1
      port: 9000
      udp: true
      level: WARNING
  modules:
    # SENSORS
    src.senses.vision: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    src.senses.audio: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    # PROCESSORS
    src.processing.vision: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    src.processing.audio: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    # REPRESENTERS
    src.representation.models: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    # MEMORIES
    src.memory.core: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    # COGNITION
    src.cognition.core: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    src.cognition.understanding: [DEBUG, INFO, WARNING, ERROR, CRITICAL] # Added Debug for Understanding
    src.cognition.decision: [DEBUG, INFO, WARNING, ERROR, CRITICAL] # Added Debug for Decision
    src.cognition.learning: [DEBUG, INFO, WARNING, ERROR, CRITICAL] # Added Debug for Learning
    # MOTOR CONTROL
    src.motor_control.core: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    src.motor_control.expression: [DEBUG, INFO, WARNING, ERROR, CRITICAL] # Added Debug for Expression
    # INTERACTION
    src.interaction.api: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    src.interaction.output_channels.console:
      [DEBUG, INFO, WARNING, ERROR, CRITICAL]
    src.interaction.output_channels.web_api: [DEBUG, INFO, WARNING, ERROR, CRITICAL] # Added Debug for WebAPI channel