# config/main_config.yaml
# Evo projesinin ana yapılandırma dosyası.
# Modül ayarları, genel parametreler ve diğer yapılandırmalar burada tanımlanır.

# Genel Ayarlar
cognitive_loop_interval: 1.0 # Bilişsel döngünün ne sıklıkta çalışacağı (saniye)

# Sense modülleri ayarları
vision:
  camera_index: 0 # Varsayılan kamera indeksi
  dummy_width: 640 # Simüle kare genişliği (gerçek kamera yoksa)
  dummy_height: 480 # Simüle kare yüksekliği (gerçek kamera yoksa)
  # is_dummy: True # Gerçek kamera yerine simülasyon kullanılsın mı? (Gelecek)

audio:
  audio_rate: 44100 # Ses örnekleme oranı
  audio_chunk_size: 1024 # Her seferinde işlenecek ses örneği sayısı
  # audio_input_device_index: null # null varsayılan cihazı kullanır, belirli bir index verilebilir.

# Processor modülleri ayarları
processors:
  vision:
    output_width: 64
    output_height: 64
    canny_low_threshold: 50 # Canny kenar tespiti düşük eşiği
    canny_high_threshold: 150 # Canny kenar tespiti yüksek eşiği
  audio:
    # output_dim: AudioProcessor'ın döndüreceği özellik sayısı (Enerji, Spectral Centroid).
    # Implementation şu an 2 özellik döndürüyor.
    output_dim: 2
    # audio_rate AudioSensor'dan gelebilir, ama burada da belirtilebilir.
    # audio_rate: 44100 # İsteğe bağlı olarak burada belirtilebilir

# Representation Learner ayarları
representation:
  # input_dim: Encoder'ın beklediği toplam girdi boyutu.
  # (VisionProcessor grayscale 64*64) + (VisionProcessor edges 64*64) + (AudioProcessor output_dim 2)
  # 4096 + 4096 + 2 = 8194
  input_dim: 8194
  representation_dim: 128 # Temsil vektörünün boyutu

# Memory modülleri ayarları
memory:
  max_memory_size: 1000 # Saklanacak maksimum temsil sayısı (core/working memory)
  num_retrieved_memories: 5 # Retrieve metodunda varsayılan olarak geri çağrılacak anı sayısı
  # Kalıcı depolama ayarları
  memory_file_path: data/core_memory.pkl # Belleğin kaydedileceği/yükleneceği dosya yolu. data/ dizini oluşturulacak.
  # retrieval_method: similarity # Gelecekte farklı method seçimi olabilir.

# Cognition modülleri ayarları
cognition:
  # Anlama (Understanding) ve Karar (Decision) ayarları
  # familiarity_threshold: Bellek benzerliğine dayalı "tanıdık" kabul etmek için gereken en düşük bellek benzerlik skoru (0.0 ile 1.0 arası float).
  familiarity_threshold: 0.8 # Varsayılan değer
  # Process çıktısı eşikleri (Process çıktı değerlerine göre ayarlanmalı. DEBUG loglarına bakın.)
  audio_energy_threshold: 1000.0 # Yüksek Ses Enerjisi Eşiği (Örnek: 1000.0 çok yüksek, ortamınıza göre ayarlayın. DEBUG loglarına bakın.)
  visual_edges_threshold: 50.0 # Yüksek Görsel Kenar Eşiği (Örnek: 50.0 orta düzeyde, ortamınıza göre ayarlayın. DEBUG loglarına bakın.)
  brightness_threshold_high: 200.0 # Parlak Ortam Eşiği (0-255 ortalama gri değerine göre. Örn: 200.0 parlak bir oda olabilir.)
  brightness_threshold_low: 50.0 # Karanlık Ortam Eşiği (0-255 ortalama gri değerine göre. Örn: 50.0 loş veya karanlık bir ortam olabilir.)
  # Öğrenme (Learning) ve Kavram Tanıma ayarları
  learning_frequency: 100 # LearningModule'ün kaç bilişsel döngü adımında bir tetikleneceği
  learning_memory_sample_size: 50 # LearningModule için Memory'den alınacak Representation sayısı
  new_concept_threshold: 0.7 # Bir Representation'ın yeni kavram sayılması için mevcut kavramlara olan en yüksek benzerlik eşiği (0.0-1.0)
  concept_recognition_threshold: 0.85 # Bir Representation'ın bilinen bir kavrama ait sayılması için gereken en yüksek benzerlik eşiği (0.0-1.0)
  # İçsel Durum (Curiosity) ayarları
  curiosity_threshold: 5.0 # Merak seviyesinin keşif/sinyal kararı için ulaşması gereken eşik
  curiosity_increment_new: 1.0 # "Yeni" input algılandığında merak seviyesi artış miktarı
  curiosity_decrement_familiar: 0.5 # "Tanıdık" input algılandığında merak seviyesi azalış miktarı
  curiosity_decay: 0.1 # Her döngü adımında merak seviyesinin otomatik azalışı


# Motor Control modülleri ayarları
motor_control:
  # Örneğin, çıktı tipi (metin, ses vb.) veya sentezleyici ayarları
  # default_output_type: text

# Interaction modülleri ayarları
interaction:
  enabled_channels: ['console'] # Aktif çıktı kanalları listesi. 'console', 'web_api' vb.
  channel_configs: # Kanal bazlı özel ayarlar
    web_api:
      port: 5000
      # host: 127.0.0.1 # Gelecekte

# Loglama Ayarları
logging:
  level: INFO
  handlers:
    - type: console
      level: DEBUG
      color: true
    - type: file
      filename: logs/evo_all.log
      level: DEBUG
      color: false
    - type: webapi
      url: http://localhost:5000/log
      level: ERROR
    - type: socket
      host: 127.0.0.1
      port: 9000
      udp: true
      level: WARNING     
  modules:
    # SENSORS
    src.senses.vision: [INFO, DEBUG]
    src.senses.audio: [INFO, WARNING]
    # PROCESSORS
    src.processing.vision: [INFO, DEBUG]
    src.processing.audio: [INFO]
    # REPRESENTERS
    src.representation.models: [INFO, WARNING]
    # MEMORIES
    src.memory.core: [INFO, DEBUG]
    # COGNITION
    src.cognition.core: [INFO, DEBUG, WARNING]
    # MOTOR CONTROL
    src.motor_control.core: [INFO]
    # INTERACTION
    src.interaction.api: [INFO, WARNING]